name: Publish npm packages
on:
  workflow_dispatch:
    inputs:
      ampversion:
        description: 'AMP version'
        required: true   
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extension: ['amp-fit-text', 'amp-video']
    steps:
    - uses: actions/checkout@v2     
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'        
        registry-url: 'https://registry.npmjs.org'
    # add step to build binaries     
    - run: node ./build-system/compile-write-package-json.js ${{matrix.extension }} ${{ github.event.inputs.ampversion }}    
    - run: cd ./extensions/{{ matrix.extension }}/1.0
    - run: cat package.json
    # - run: npm publish --access public --prefix=${{ GITHUB_WORKSPACE }}/extensions/{{  matrix.extension  }}
    #   env: 
    #     # TODO: replace with ${{ secrets.NPM_TOKEN }}
    #     NODE_AUTH_TOKEN: //TODO

